jobs:
  include:
    - stage: build
      language: node_js
      node_js:
        - "10"
      script:
        - npm install
        - npm run docz:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
stages:
  - name: deploy
    if: branch = master AND type != pull_request